# Use Bitnami legacy Spark image
FROM bitnamilegacy/spark:3.5.0

USER root

# ----------------------------------------------------
# System dependencies
# ----------------------------------------------------
RUN apt-get update && \
    apt-get install -y \
        libpq-dev \
        net-tools \
        iputils-ping \
        iproute2 \
        dnsutils \
        telnet \
        netcat-openbsd \
        curl \
        wget && \
    rm -rf /var/lib/apt/lists/*

# ----------------------------------------------------
# Spark Dependencies (Iceberg + S3 + JDBC)
# ----------------------------------------------------
WORKDIR /opt/bitnami/spark/jars

# Iceberg Spark Runtime (Spark 3.5 + Scala 2.12)
RUN wget https://repo1.maven.org/maven2/org/apache/iceberg/iceberg-spark-runtime-3.5_2.12/1.5.2/iceberg-spark-runtime-3.5_2.12-1.5.2.jar

# Hadoop AWS (S3A support)
RUN wget https://repo1.maven.org/maven2/org/apache/hadoop/hadoop-aws/3.3.4/hadoop-aws-3.3.4.jar

# AWS SDK Bundle
RUN wget https://repo1.maven.org/maven2/com/amazonaws/aws-java-sdk-bundle/1.12.262/aws-java-sdk-bundle-1.12.262.jar

# PostgreSQL JDBC Driver
RUN wget https://repo1.maven.org/maven2/org/postgresql/postgresql/42.6.0/postgresql-42.6.0.jar

# Return to Bitnami runtime user
USER 1001